name: Test Action
on: [push]
jobs:
  get_num_square:
    runs-on: ubuntu-latest
    name: Returns the square of the number
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Fetch num squared
        id: get-square
        uses: ./
        with:
          num: 5
      - name: Print the square
        run: echo "The square of 5 is ${{ steps.get-square.outputs.num_squared }}"